image: python:3

types:
  - build
  - test

build_app:
  type: build
  script:
    - pip install -r requirements.txt

test_app:
  type: test
  script:
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - which nosetests
    - nosetests
