version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          sudo pip install awscli 
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t mvasilenko/telegram-bot-kievradar:$TAG .      # (3)
      - deploy:
          name: Push application Docker image
          command: |
            login="$(aws ecr get-login |sed 's/-e none//')"
            ${login}
            echo "ecr_ep=${ECR_ENDPOINT}"
            docker tag app "${ECR_ENDPOINT}/telegram-bot-kievradar:${CIRCLE_SHA1}"
            docker push "${ECR_ENDPOINT}/telegram-bot-kievradar:${CIRCLE_SHA1}"
# login to docker hub and push the image
#          docker login -u $DOCKER_USER -p $DOCKER_PASS         # (4)
#          docker push mvasilenko/telegram-bot-kievradar:$TAG
