version: 2
jobs:
  build:
#    working_directory: /app
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          sudo pip install awscli 
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $CIRCLE_PROJECT_REPONAME .
      - deploy:
          name: Push application Docker image
          command: |
            eval "$(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)"
            docker tag $CIRCLE_PROJECT_REPONAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CIRCLE_PROJECT_REPONAME:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CIRCLE_PROJECT_REPONAME:latest
# login to docker hub and push the image
#          docker login -u $DOCKER_USER -p $DOCKER_PASS         # (4)
#          docker push mvasilenko/telegram-bot-kievradar:$TAG
