version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          sudo pip install awscli
          sudo apt-get install jq
      # build docker image locally and tag it by repo name and commit hash
      - run: |
          docker build -t $CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 .
      - deploy:
          name: Push application Docker image
          command: |
            CLUSTER="$CIRCLE_PROJECT_REPONAME"
            FAMILY="$CIRCLE_PROJECT_REPONAME"
            DOCKER_IMAGE=$CIRCLE_PROJECT_REPONAME
            TASK="$CIRCLE_PROJECT_REPONAME"
            SERVICE="$CIRCLE_PROJECT_REPONAME-service"

            # login to AWS ECR repo, this command is equialent of " docker login -u AWS -p HUGE_PASSWORD AMAZON_ID.dkr.ecr.AWS_REGION.amazonaws.com
            eval "$(aws ecr get-login --region $AWS_DEFAULT_REGION | sed -e 's/-e none//g')"
            # tag locally built image with repo name and commit hash
            docker tag $CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
            # push tagged image to the repo
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1

            # create task for docker deploy
            # "portMappings": [
            #   {
            #     "containerPort": 3000,
            #     "hostPort": 80
            #   }
            # ],

            # Describe task template and fill it
            task_template='[
              {
                "name": "%s",
                "image": "%s.dkr.ecr.%s.amazonaws.com/%s:%s",
                "essential": true,
                "memoryReservation": 10,
                "environment" : [
                    { "name" : "TOKEN_BOT", "value" : "%s" }
                ]
              }
            ]'

            task_def=$(printf "$task_template" $TASK $AWS_ACCOUNT_ID $AWS_DEFAULT_REGION $DOCKER_IMAGE $CIRCLE_SHA1 $TOKEN_BOT)

            # Register task definition
            json=$(aws ecs register-task-definition --container-definitions "$task_def" --family "$FAMILY")

            # Grab revision # using regular bash and grep
            revision=$(echo "$json" | grep -o '"revision": [0-9]*' | grep -Eo '[0-9]+')

            # Deploy revision
            aws ecs update-service --cluster "$CLUSTER" --service "$SERVICE" --task-definition "$TASK":"$revision"
