version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          sudo pip install -r requirements.txt
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t mvasilenko/telegram-bot-kievradar:$TAG .      # (3)
          docker login -u $DOCKER_USER -p $DOCKER_PASS         # (4)
          docker push mvasilenko/telegram-bot-kievradar:$TAG             
